const questions = [
  {
    id: 1,
    question:
      "وقتی در یک جمع هستی و ناگهان همه سکوت می‌کنند، چه کاری انجام می‌دهی؟",
    options: [
      {
        text: "از سکوت استقبال می‌کنم و در افکار خودم غرق می‌شوم.",
        scores: {
          dexter: 4,
          brian: 0,
          harry: 4,
          matthews: 0,
          doakes: 3,
          rita: 0,
          laguerta: 2,
          debra: 0,
          batista: 0,
          masuka: 0,
          quinn: 2,
        },
      },
      {
        text: "سعی می‌کنم با شوخی و شیطنت دوباره فضا را گرم کنم.",
        scores: {
          dexter: 0,
          brian: 2,
          harry: 0,
          matthews: 0,
          doakes: 0,
          rita: 0,
          laguerta: 0,
          debra: 2,
          batista: 2,
          masuka: 4,
          quinn: 3,
        },
      },
      {
        text: "کمی کسل می‌شوم و یک بحثی را شروع می‌کنم.",
        scores: {
          dexter: 0,
          brian: 0,
          harry: 0,
          matthews: 0,
          doakes: 0,
          rita: 0,
          laguerta: 0,
          debra: 4,
          batista: 3,
          masuka: 0,
          quinn: 0,
        },
      },
      {
        text: "فقط بقیه را تماشا می‌کنم و به شکل مختصر واکنش نشان می‌دهم.",
        scores: {
          dexter: 2,
          brian: 4,
          harry: 0,
          matthews: 3,
          doakes: 4,
          rita: 4,
          laguerta: 0,
          debra: 0,
          batista: 0,
          masuka: 0,
          quinn: 2,
        },
      },
    ],
  },
  {
    id: 2,
    question: "وقتی در یک موقعیت بحرانی قرار می‌گیری، چه واکنشی نشان می‌دهی؟",
    options: [
      {
        text: " تحت تأثیر قرار می‌گیرم و استرسی می‌شوم.",
        scores: {
          dexter: 0,
          brian: 0,
          harry: 0,
          matthews: 0,
          doakes: 4,
          rita: 4,
          laguerta: 0,
          debra: 4,
          batista: 0,
          masuka: 0,
          quinn: 4,
        },
      },
      {
        text: "آرامش خودم را حفظ می‌کنم و واکنش شدیدی نشان نمی‌دهم.",
        scores: {
          dexter: 4,
          brian: 0,
          harry: 0,
          matthews: 0,
          doakes: 0,
          rita: 0,
          laguerta: 4,
          debra: 0,
          batista: 0,
          masuka: 0,
          quinn: 0,
        },
      },
      {
        text: "کمی آشفته می‌شوم ولی سعی می‌کنم خودم را کنترل کنم.",
        scores: {
          dexter: 0,
          brian: 0,
          harry: 0,
          matthews: 0,
          doakes: 0,
          rita: 0,
          laguerta: 0,
          debra: 0,
          batista: 4,
          masuka: 0,
          quinn: 0,
        },
      },
      {
        text: "به آرامی به وضعیت نگاه می‌کنم و قدم به قدم تصمیم می‌گیرم.",
        scores: {
          dexter: 3,
          brian: 4,
          harry: 4,
          matthews: 4,
          doakes: 0,
          rita: 0,
          laguerta: 3,
          debra: 0,
          batista: 0,
          masuka: 4,
          quinn: 0,
        },
      },
    ],
  },
  {
    id: 3,
    question: "وقتی با مشکلات شخصی‌ات روبه‌رو می‌شوی، معمولاً چه واکنشی داری؟",
    options: [
      {
        text: "دوست دارم راجع به آن با افرادی که به آن‌ها اعتماد دارم صحبت کنم.",
        scores: {
          dexter: 0,
          brian: 0,
          harry: 0,
          matthews: 0,
          doakes: 0,
          rita: 0,
          laguerta: 0,
          debra: 4,
          batista: 4,
          masuka: 0,
          quinn: 0,
        },
      },
      {
        text: "دلم نمی‌خواهد کسی از آن باخبر شود و ترجیح می‌دهم خودم آن را حل کنم.",
        scores: {
          dexter: 4,
          brian: 4,
          harry: 0,
          matthews: 0,
          doakes: 4,
          rita: 0,
          laguerta: 3,
          debra: 0,
          batista: 0,
          masuka: 0,
          quinn: 0,
        },
      },
      {
        text: "فقط در مواقع بحرانی و دشوار، از دیگران کمک می‌خواهم.",
        scores: {
          dexter: 0,
          brian: 0,
          harry: 4,
          matthews: 4,
          doakes: 3,
          rita: 0,
          laguerta: 4,
          debra: 0,
          batista: 0,
          masuka: 0,
          quinn: 4,
        },
      },
      {
        text: "به سرعت با دیگران صحبت می‌کنم و نظر یا راهنمایی آن‌ها را می‌پرسم.",
        scores: {
          dexter: 0,
          brian: 0,
          harry: 0,
          matthews: 0,
          doakes: 0,
          rita: 4,
          laguerta: 0,
          debra: 2,
          batista: 3,
          masuka: 4,
          quinn: 0,
        },
      },
    ],
  },
  {
    id: 4,
    question: "وقتی تصمیمی می‌گیری، معمولاً چه رویکردی داری؟",
    options: [
      {
        text: "به تأثیر تصمیمم روی احساسات دیگران فکر می‌کنم.",
        scores: {
          dexter: 0,
          brian: 0,
          harry: 4,
          matthews: 0,
          doakes: 0,
          rita: 4,
          laguerta: 0,
          debra: 4,
          batista: 3,
          masuka: 0,
          quinn: 4,
        },
      },
      {
        text: "منافع شخصی خودم را در اولویت قرار می‌دهم.",
        scores: {
          dexter: 0,
          brian: 4,
          harry: 0,
          matthews: 4,
          doakes: 0,
          rita: 0,
          laguerta: 4,
          debra: 0,
          batista: 0,
          masuka: 0,
          quinn: 0,
        },
      },
      {
        text: "علیرغم احساساتم، در نهایت تصمیمم بر پایه منطق است.",
        scores: {
          dexter: 0,
          brian: 0,
          harry: 0,
          matthews: 0,
          doakes: 0,
          rita: 0,
          laguerta: 4,
          debra: 0,
          batista: 4,
          masuka: 0,
          quinn: 0,
        },
      },
      {
        text: "منطق اولویت من است.",
        scores: {
          dexter: 4,
          brian: 0,
          harry: 0,
          matthews: 0,
          doakes: 4,
          rita: 0,
          laguerta: 4,
          debra: 0,
          batista: 0,
          masuka: 0,
          quinn: 0,
        },
      },
    ],
  },
  {
    id: 5,
    question: "وقتی از چیزی ناراحت هستی، معمولاً چطور رفتار می‌کنی؟",
    options: [
      {
        text: "احساسم کاملاً مشخص است و اطرافیان سریع متوجه می‌شوند.",
        scores: {
          dexter: 0,
          brian: 0,
          harry: 0,
          matthews: 0,
          doakes: 2,
          rita: 4,
          laguerta: 0,
          debra: 4,
          batista: 0,
          masuka: 2,
          quinn: 0,
        },
      },
      {
        text: "هیچ چیز بروز نمی‌دهم و ناراحتی‌ام را در خودم نگه می‌دارم.",
        scores: {
          dexter: 4,
          brian: 4,
          harry: 4,
          matthews: 4,
          doakes: 0,
          rita: 0,
          laguerta: 4,
          debra: 0,
          batista: 0,
          masuka: 0,
          quinn: 0,
        },
      },
      {
        text: "رفتارم تغییر می‌کند، اما مستقیماً چیزی نمی‌گویم.",
        scores: {
          dexter: 0,
          brian: 0,
          harry: 0,
          matthews: 0,
          doakes: 0,
          rita: 0,
          laguerta: 0,
          debra: 0,
          batista: 0,
          masuka: 4,
          quinn: 4,
        },
      },
      {
        text: "ناراحتی‌ام را بیان می‌کنم و درباره‌اش توضیح می‌دهم.",
        scores: {
          dexter: 0,
          brian: 0,
          harry: 0,
          matthews: 0,
          doakes: 0,
          rita: 4,
          laguerta: 0,
          debra: 4,
          batista: 4,
          masuka: 0,
          quinn: 0,
        },
      },
    ],
  },
  {
    id: 6,
    question: "از انجام کدام کار بیشتر لذت می‌بری؟",
    options: [
      {
        text: "تماشا کردن افراد و تحلیل رفتارشان",
        scores: {
          dexter: 3,
          brian: 4,
          harry: 0,
          matthews: 0,
          doakes: 4,
          rita: 0,
          laguerta: 0,
          debra: 0,
          batista: 0,
          masuka: 0,
          quinn: 0,
        },
      },
      {
        text: "شوخی کردن و مرکز توجه قرار گرفتن",
        scores: {
          dexter: 0,
          brian: 0,
          harry: 0,
          matthews: 0,
          doakes: 0,
          rita: 0,
          laguerta: 0,
          debra: 0,
          batista: 0,
          masuka: 4,
          quinn: 0,
        },
      },
      {
        text: "صحبت کردن و همراهی کردن با دیگران",
        scores: {
          dexter: 0,
          brian: 0,
          harry: 0,
          matthews: 0,
          doakes: 0,
          rita: 3,
          laguerta: 0,
          debra: 4,
          batista: 4,
          masuka: 0,
          quinn: 3,
        },
      },
      {
        text: "غرق شدن در افکار و فعالیت‌های شخصی خود.",
        scores: {
          dexter: 4,
          brian: 3,
          harry: 4,
          matthews: 0,
          doakes: 3,
          rita: 0,
          laguerta: 4,
          debra: 0,
          batista: 0,
          masuka: 0,
          quinn: 0,
        },
      },
    ],
  },
  {
    id: 7,
    question:
      "وقتی حقیقت چیزی را می‌فهمی، معمولاً این اتفاق از چه راهی رخ می‌دهد؟",
    options: [
      {
        text: "یک حس درونی به من می‌گوید که این حقیقت ماجرا است.",
        scores: {
          dexter: 4,
          brian: 0,
          harry: 4,
          matthews: 0,
          doakes: 4,
          rita: 0,
          laguerta: 1,
          debra: 0,
          batista: 0,
          masuka: 0,
          quinn: 4,
        },
      },
      {
        text: "با فکر کردن و کنار هم گذاشتن اطلاعات به پاسخ می‌رسم.",
        scores: {
          dexter: 4,
          brian: 0,
          harry: 0,
          matthews: 0,
          doakes: 0,
          rita: 0,
          laguerta: 0,
          debra: 4,
          batista: 0,
          masuka: 0,
          quinn: 0,
        },
      },
      {
        text: "گاهی خواب یا یک احساس ناگهانی باعث می‌شود حقیقت را بفهمم.",
        scores: {
          dexter: 2,
          brian: 0,
          harry: 0,
          matthews: 0,
          doakes: 4,
          rita: 0,
          laguerta: 0,
          debra: 0,
          batista: 0,
          masuka: 0,
          quinn: 0,
        },
      },
      {
        text: "با آزمودن و مشاهده مستقیم چیزها به حقیقت می‌رسم.",
        scores: {
          dexter: 0,
          brian: 0,
          harry: 0,
          matthews: 3,
          doakes: 0,
          rita: 0,
          laguerta: 3,
          debra: 2,
          batista: 4,
          masuka: 0,
          quinn: 3,
        },
      },
    ],
  },
  {
    id: 8,
    question: "در مورد راستگویی و دروغ گفتن، کدام یک بیشتر با تو همخوانی دارد؟",
    options: [
      {
        text: "دروغ گفتن برایم سخت است و همیشه سعی می‌کنم صادق باشم.",
        scores: {
          dexter: 0,
          brian: 0,
          harry: 4,
          matthews: 3,
          doakes: 2,
          rita: 4,
          laguerta: 0,
          debra: 3,
          batista: 0,
          masuka: 0,
          quinn: 3,
        },
      },
      {
        text: "به راحتی می‌توانم دروغی قابل باور بگویم.",
        scores: {
          dexter: 4,
          brian: 4,
          harry: 0,
          matthews: 0,
          doakes: 0,
          rita: 0,
          laguerta: 4,
          debra: 0,
          batista: 0,
          masuka: 0,
          quinn: 0,
        },
      },
      {
        text: "صداقت انتخاب من است.",
        scores: {
          dexter: 0,
          brian: 0,
          harry: 3,
          matthews: 0,
          doakes: 0,
          rita: 3,
          laguerta: 0,
          debra: 3,
          batista: 4,
          masuka: 0,
          quinn: 0,
        },
      },
      {
        text: "در بعضی موقعیت‌ها، دروغ بخشی از زندگی من است.",
        scores: {
          dexter: 4,
          brian: 4,
          harry: 0,
          matthews: 0,
          doakes: 0,
          rita: 0,
          laguerta: 4,
          debra: 0,
          batista: 0,
          masuka: 0,
          quinn: 0,
        },
      },
    ],
  },
  {
    id: 9,
    question: "در زندگی روزمره، معمولاً چه رویکردی داری؟",
    options: [
      {
        text: "دوست دارم همه چیز دقیق و منظم باشد و طبق برنامه پیش برود.",
        scores: {
          dexter: 4,
          brian: 4,
          harry: 4,
          matthews: 4,
          doakes: 4,
          rita: 0,
          laguerta: 4,
          debra: 0,
          batista: 0,
          masuka: 4,
          quinn: 0,
        },
      },
      {
        text: "تا حد زیادی به برنامه‌ها پایبندم اما انعطاف هم دارم.",
        scores: {
          dexter: 0,
          brian: 0,
          harry: 0,
          matthews: 0,
          doakes: 0,
          rita: 4,
          laguerta: 1,
          debra: 3,
          batista: 4,
          masuka: 0,
          quinn: 0,
        },
      },
      {
        text: "از چارچوب‌ها و قوانین مشخص متنفرم و ترجیح می‌دهم آزاد عمل کنم.",
        scores: {
          dexter: 0,
          brian: 0,
          harry: 0,
          matthews: 0,
          doakes: 0,
          rita: 0,
          laguerta: 0,
          debra: 0,
          batista: 0,
          masuka: 0,
          quinn: 4,
        },
      },
      {
        text: "منعطف عمل میکنم",
        scores: {
          dexter: 0,
          brian: 0,
          harry: 0,
          matthews: 0,
          doakes: 0,
          rita: 0,
          laguerta: 1,
          debra: 4,
          batista: 0,
          masuka: 0,
          quinn: 0,
        },
      },
    ],
  },
  {
    id: 10,
    question: "در کارهای گروهی، معمولاً چه نقش‌ای داری؟",
    options: [
      {
        text: "رهبر و هدایتگر تیم هستم.",
        scores: {
          dexter: 0,
          brian: 0,
          harry: 0,
          matthews: 4,
          doakes: 3,
          rita: 0,
          laguerta: 4,
          debra: 3,
          batista: 3,
          masuka: 0,
          quinn: 0,
        },
      },
      {
        text: "حمایت‌کننده و همراهی‌کننده اعضای تیم هستم.",
        scores: {
          dexter: 0,
          brian: 0,
          harry: 0,
          matthews: 0,
          doakes: 0,
          rita: 0,
          laguerta: 0,
          debra: 3,
          batista: 4,
          masuka: 3,
          quinn: 2,
        },
      },
      {
        text: "تمرکز روی کار خودم دارم و دخالت زیادی نمی‌کنم.",
        scores: {
          dexter: 4,
          brian: 4,
          harry: 4,
          matthews: 0,
          doakes: 0,
          rita: 4,
          laguerta: 0,
          debra: 0,
          batista: 0,
          masuka: 0,
          quinn: 0,
        },
      },
      {
        text: "نقش‌های مختلف را امتحان می‌کنم و سازگار با شرایط هستم.",
        scores: {
          dexter: 3,
          brian: 0,
          harry: 0,
          matthews: 0,
          doakes: 0,
          rita: 0,
          laguerta: 1,
          debra: 2,
          batista: 0,
          masuka: 0,
          quinn: 0,
        },
      },
    ],
  },
  {
    id: 11,
    question: "چقدر به ایده‌ها و نظرات جدید علاقه‌مندی؟",
    options: [
      {
        text: "همیشه مشتاق یادگیری و امتحان ایده‌های جدید هستم.",
        scores: {
          dexter: 1,
          brian: 0,
          harry: 0,
          matthews: 0,
          doakes: 0,
          rita: 0,
          laguerta: 0,
          debra: 2,
          batista: 4,
          masuka: 3,
          quinn: 0,
        },
      },
      {
        text: "گاهی ایده‌ها را بررسی می‌کنم اما معمولاً به تجربه گذشته اعتماد دارم.",
        scores: {
          dexter: 2,
          brian: 0,
          harry: 0,
          matthews: 4,
          doakes: 0,
          rita: 0,
          laguerta: 3,
          debra: 4,
          batista: 0,
          masuka: 0,
          quinn: 0,
        },
      },
      {
        text: "به ایده‌های جدید علاقه کمی دارم و ترجیح می‌دهم همان روش‌های آشنا را دنبال کنم.",
        scores: {
          dexter: 3,
          brian: 0,
          harry: 0,
          matthews: 0,
          doakes: 0,
          rita: 0,
          laguerta: 4,
          debra: 3,
          batista: 0,
          masuka: 0,
          quinn: 4,
        },
      },
      {
        text: "به سختی تغییر می‌کنم و کمتر نظرات جدید را می‌پذیرم.",
        scores: {
          dexter: 4,
          brian: 4,
          harry: 0,
          matthews: 0,
          doakes: 4,
          rita: 0,
          laguerta: 3,
          debra: 0,
          batista: 0,
          masuka: 0,
          quinn: 0,
        },
      },
    ],
  },
  {
    id: 12,
    question: "وقتی وارد یک محیط جدید می‌شوی، معمولاً چه می‌کنی؟",
    options: [
      {
        text: "به تمام جزئیات محیط توجه می‌کنم و چیزهای کوچک را به یاد می‌سپارم.",
        scores: {
          dexter: 4,
          brian: 0,
          harry: 0,
          matthews: 0,
          doakes: 0,
          rita: 0,
          laguerta: 0,
          debra: 0,
          batista: 0,
          masuka: 4,
          quinn: 0,
        },
      },
      {
        text: "محیط را به طور کلی می‌بینم و فقط نکات مهم را به خاطر می‌سپارم.",
        scores: {
          dexter: 0,
          brian: 0,
          harry: 0,
          matthews: 0,
          doakes: 0,
          rita: 0,
          laguerta: 4,
          debra: 4,
          batista: 0,
          masuka: 0,
          quinn: 0,
        },
      },
      {
        text: "کمتر به جزئیات توجه می‌کنم و بیشتر روی کار یا هدف خودم تمرکز دارم.",
        scores: {
          dexter: 0,
          brian: 4,
          harry: 0,
          matthews: 0,
          doakes: 4,
          rita: 0,
          laguerta: 0,
          debra: 0,
          batista: 0,
          masuka: 0,
          quinn: 0,
        },
      },
      {
        text: "معمولاً اصلاً متوجه جزئیات نمی‌شوم و فقط به محیط به شکل کلی نگاه می‌کنم.",
        scores: {
          dexter: 0,
          brian: 0,
          harry: 0,
          matthews: 4,
          doakes: 0,
          rita: 4,
          laguerta: 0,
          debra: 0,
          batista: 4,
          masuka: 0,
          quinn: 4,
        },
      },
    ],
  },
  {
    id: 13,
    question:
      "وقتی با قوانینی مواجه می‌شوی که به نظرت محدودکننده‌اند، چه واکنشی داری؟",
    options: [
      {
        text: "قوانین را رعایت می‌کنم اما همیشه دنبال راهی هستم که کمی از آن فراتر بروم.",
        scores: {
          dexter: 0,
          brian: 0,
          harry: 4,
          matthews: 0,
          doakes: 0,
          rita: 0,
          laguerta: 4,
          debra: 0,
          batista: 0,
          masuka: 0,
          quinn: 0,
        },
      },
      {
        text: "سخت به قوانین پایبندم و ترجیح می‌دهم ریسک نکنم.",
        scores: {
          dexter: 0,
          brian: 0,
          harry: 0,
          matthews: 0,
          doakes: 3,
          rita: 4,
          laguerta: 0,
          debra: 0,
          batista: 4,
          masuka: 3,
          quinn: 0,
        },
      },
      {
        text: "گاهی قوانین را نادیده می‌گیرم، به شرطی که خطری نداشته باشد.",
        scores: {
          dexter: 0,
          brian: 0,
          harry: 0,
          matthews: 4,
          doakes: 0,
          rita: 0,
          laguerta: 0,
          debra: 0,
          batista: 0,
          masuka: 0,
          quinn: 4,
        },
      },
      {
        text: "قوانین را کلاً نادیده می‌گیرم و بر اساس خواسته‌هایم عمل می‌کنم.",
        scores: {
          dexter: 4,
          brian: 4,
          harry: 0,
          matthews: 0,
          doakes: 0,
          rita: 0,
          laguerta: 0,
          debra: 2,
          batista: 0,
          masuka: 0,
          quinn: 0,
        },
      },
    ],
  },
  {
    id: 14,
    question:
      "وقتی با موقعیتی روبه‌رو می‌شوی که نیاز به شجاعت دارد، معمولاً چه می‌کنی؟",
    options: [
      {
        text: "بی‌تردید وارد می‌شوم و وظیفه‌ام را انجام می‌دهم.",
        scores: {
          dexter: 4,
          brian: 0,
          harry: 0,
          matthews: 4,
          doakes: 4,
          rita: 0,
          laguerta: 0,
          debra: 4,
          batista: 4,
          masuka: 0,
          quinn: 4,
        },
      },
      {
        text: "ابتدا وضعیت را بررسی می‌کنم و بعد اقدام می‌کنم.",
        scores: {
          dexter: 0,
          brian: 4,
          harry: 0,
          matthews: 0,
          doakes: 0,
          rita: 0,
          laguerta: 0,
          debra: 0,
          batista: 0,
          masuka: 0,
          quinn: 0,
        },
      },
      {
        text: "معمولاً محتاط عمل می‌کنم و فقط وقتی مطمئن باشم وارد می‌شوم.",
        scores: {
          dexter: 0,
          brian: 0,
          harry: 0,
          matthews: 0,
          doakes: 0,
          rita: 0,
          laguerta: 0,
          debra: 0,
          batista: 0,
          masuka: 4,
          quinn: 0,
        },
      },
      {
        text: "اغلب از موقعیت فاصله می‌گیرم یا به دیگران واگذار می‌کنم.",
        scores: {
          dexter: 0,
          brian: 0,
          harry: 0,
          matthews: 4,
          doakes: 0,
          rita: 4,
          laguerta: 4,
          debra: 0,
          batista: 0,
          masuka: 0,
          quinn: 0,
        },
      },
    ],
  },
  {
    id: 15,
    question: "چقدر راحت در جمع ایده‌ها و نظرات خودت را بیان می‌کنی؟",
    options: [
      {
        text: "بدون هیچ تردیدی همه ایده‌هایم را بیان می‌کنم.",
        scores: {
          dexter: 0,
          brian: 0,
          harry: 0,
          matthews: 0,
          doakes: 0,
          rita: 0,
          laguerta: 0,
          debra: 3,
          batista: 4,
          masuka: 4,
          quinn: 3,
        },
      },
      {
        text: "معمولاً فقط وقتی احساس راحتی کنم نظرم را می‌گویم.",
        scores: {
          dexter: 0,
          brian: 0,
          harry: 0,
          matthews: 0,
          doakes: 0,
          rita: 4,
          laguerta: 0,
          debra: 4,
          batista: 0,
          masuka: 0,
          quinn: 0,
        },
      },
      {
        text: "کمتر صحبت می‌کنم و ترجیح می‌دهم گوش دهم.",
        scores: {
          dexter: 0,
          brian: 4,
          harry: 3,
          matthews: 4,
          doakes: 4,
          rita: 0,
          laguerta: 0,
          debra: 0,
          batista: 0,
          masuka: 0,
          quinn: 0,
        },
      },
      {
        text: "تقریباً هیچ وقت در جمع نظرم را نمی‌گویم و محتاط هستم.",
        scores: {
          dexter: 4,
          brian: 0,
          harry: 0,
          matthews: 0,
          doakes: 0,
          rita: 0,
          laguerta: 0,
          debra: 0,
          batista: 0,
          masuka: 0,
          quinn: 0,
        },
      },
    ],
  },
];

const start_container = document.querySelector(".start-container");
const startGame = document.querySelector(".startGame");
const category = document.querySelector(".category");
const Dexter = document.querySelector(".Dexter");
const questionBox = document.querySelector(".question-box");

startGame.addEventListener("click", () => {
  start_container.classList.add("hidden");
  category.classList.remove("hidden");
});
Dexter.addEventListener("click", () => {
  category.classList.add("hidden");
  questionBox.classList.remove("hidden");
});
